title: Pearson Tran | CS Student @ Uwaterloo
description: Welcome! Pls hire me for my fall co-op term
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false
google_analytics:
